# ./github/workflows/django.yml

name: Django CI # Título da Ação (Action)

on: [push, pull_request] # Evento que irá ser chamado quando houver um push ou pull_request em qualquer branch

jobs: # Trabalhos a serem executados nessa action
  build: # Trabalho de Build
    runs-on: ubuntu-latest # O tipo da máquina em que será executado os comandos

    steps: # Passos (steps) que esse trabalho faz
    - uses: actions/checkout@v3 # Checa nosso repositório fazendo um clone e pegando informações de chaves secretas

    - name: Set up Python 3.12.0 # Nome do passo
      uses: actions/setup-python@v3 # Instala o Python 3.12.0
      with:
        python-version: 3.12.0

    - name: Install Dependencies # Nome do passo e em seguida o que será executado no terminal
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test